### ISSUE TITLE
请求增加network=host模式

### ISSUE THREAD

**Issue by bbpp222006** [wulabing/xray_docker#1]
docker默认使用bridge模式时，nat类型不能达到1，在玩一些p2p联机游戏时有限制。
使用network=host模式可以做到和vps的主机nat类型一致，达成游戏加速的效果。

**Comment by wulabing** [comment]
好的，会在后续版本补充

**Comment by wulabing** [comment]
久等了，更新后应该可以正常支持 host 模式

**Comment by bbpp222006** [comment]
感谢
