### ISSUE TITLE
恳请更新一下Xray Core

### ISSUE THREAD

**Issue by ptxlin** [wulabing/xray_docker#4]
已经使用wulabing大佬的docker版本的xray vision近一年，极为稳定，感谢大佬无私贡献。
Xray最新版本是1.8.10，内置的好像无法自己更新。
烦请得空的时候研究研究？

**Comment by wulabing** [comment]
客气了，我会尽快更新内置的xray版本

**Comment by ptxlin** [comment]
谢谢

**Comment by wulabing** [comment]
已经触发相关构建，等待构建完成之后能使用到目前最新版本 xray core 的镜像了
